sbol_local-cli.php basic/Valid_BasicPartTest.xml > basic/Valid_BasicPartTest.sbol.xml
sbol_local-cli.php basic/Valid_MultiSOTypesTest.xml > basic/Valid_MultiSOTypesTest.sbol.xml
sbol_local-cli.php basic/Valid_NicknameTest.xml > basic/Valid_NicknameTest.sbol.xml
sbol_local-cli.php basic/Valid_SequenceTest.xml > basic/Valid_SequenceTest.sbol.xml
sbol_local-cli.php basic/Valid_SOTypeTest.xml > basic/Valid_SOTypeTest.sbol.xml
sbol_local-cli.php extendsSbol/ValidCustomElementExtenedPartTest.xml > extendsSbol/ValidCustomElementExtenedPartTest.sbol.xml
sbol_local-cli.php subparts/Valid_DeepSubpartTest.xml > subparts/Valid_DeepSubpartTest.sbol.xml
sbol_local-cli.php subparts/Valid_MultiDeepSubpartsTest.xml > subparts/Valid_MultiDeepSubpartsTest.sbol.xml
sbol_local-cli.php subparts/Valid_SpecifiedSubcarsTest.xml > subparts/Valid_SpecifiedSubcarsTest.sbol.xml
sbol_local-cli.php subparts/Valid_SpecifiedSubpartsSubscarsTest.xml > subparts/Valid_SpecifiedSubpartsSubscarsTest.sbol.xml
sbol_local-cli.php subparts/Valid_SpecifiedSubpartsTest.xml > subparts/Valid_SpecifiedSubpartsTest.sbol.xml
